local o = vim.opt
o.completeopt = 'menuone,noselect'
o.expandtab = true
o.ignorecase = true
o.mouse = 'a'
o.smartcase = true
o.showmode = false
o.shiftwidth = 4
o.termguicolors = true
o.title = true
o.foldmethod = 'marker'
o.number = true
o.relativenumber = true
o.signcolumn = 'yes'
